---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["crime"]
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 1
        clf_lr: 0.01
        clf_weight_decay: 0.0
    adversaries:
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 1
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: True
minimizers:
  - minimizer: "mi"
    mi_max_buckets: 5
    mi_n_epochs: 5
    mi_weight: [0, 0.001, 0.005, 0.01, 0.1, 0.2, 0.5, 0.7, 1]
seed: 123
device: "cpu"
num_workers: 12
logger_level: "INFO"
out_dir: "final_results/crime"
