---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSEmployment", "ACSIncome"]
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
evaluations:
  - classifiers:
      - clf_1:
        clf_type: "normal"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
  - classifiers:
      - clf_2:
        clf_type: "dp"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_dp_noise: 1
  - classifiers:
      - clf_3:
        clf_type: "dp"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_dp_noise: 2
  - classifiers:
      - clf_4:
        clf_type: "dp"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_dp_noise: 5
  - classifiers:
      - clf_5:
        clf_type: "dp"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_dp_noise: 10
  # - classifiers:
  #     - clf_6:
  #       clf_type: "dp"
  #       clf_model: "mlp2"
  #       clf_epochs: 20
  #       clf_lr: 0.01
  #       clf_weight_decay: 0.0
  #       clf_dp_noise: 0.5
  # - classifiers:
  #     - clf_7:
  #       clf_type: "dp"
  #       clf_model: "mlp2"
  #       clf_epochs: 20
  #       clf_lr: 0.01
  #       clf_weight_decay: 0.0
  #       clf_dp_noise: 1.5
  # - classifiers:
  #     - clf_8:
  #       clf_type: "dp"
  #       clf_model: "mlp2"
  #       clf_epochs: 20
  #       clf_lr: 0.01
  #       clf_weight_decay: 0.0
  #       clf_dp_noise: 2.5
minimizers:
  - minimizer: "tree"
    tree_max_leaf_nodes: [10, 20, 50, 100, 200]
    tree_min_sample_leaf: 100
    tree_alpha: [0.0, 0.1, 0.5, 0.7]
    min_bucket_threshold: [0.1, 0.2, 0.3, 0.5, 0.6, 0.7, 0.8, 0.9]
connect_arg_lists: False
seed: 123
device: "cuda:0"
num_workers: 8
out_dir: "ablation/dp_thresh"
