---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: "ACSIncome"
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
    train_percent: 1.0
    bucketization_percent: 1.0
evaluations:
  - adversaries:
      - adv_1:
        adv_type: "linkage"
        linkage_algorithm: "random"
        linkage_b_features: [6]
        linkage_a_features: [5]
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_tune_wd: True
      - adv_2:
        adv_type: "linkage"
        linkage_algorithm: "mostlikely"
        linkage_b_features: [6]
        linkage_a_features: [5]
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_tune_wd: True
minimizers:
  - minimizer: "advtrain"
    advtrain_max_buckets: 5
    advtrain_n_epochs: 20
    advtrain_inner_steps: 1
    advtrain_weight: [0, 0.01, 0.1, 0.2, 0.3, 0.5, 0.7, 0.9, 0.95]
  - minimizer: "mi"
    mi_max_buckets: 5
    mi_n_epochs: 20
    mi_weight: [0, 0.001, 0.005, 0.01, 0.1, 0.2, 0.5, 0.7, 1]
  - minimizer: "uniform"
    uniform_buckets: [1, 2, 3, 4, 5]
  - minimizer: "tree"
    tree_max_leaf_nodes: [2, 4, 6, 8, 10, 20, 50, 100, 200]
    tree_min_sample_leaf: 100
    tree_alpha: [0.0, 0.1, 0.3, 0.5, 0.6, 0.65, 0.7, 0.75, 0.8, 0.85, 0.9, 0.95]
  - minimizer: "featsel"
    featsel_k: [2, 4, 8, 10, 20]
seed: 123123
device: "cpu"
num_workers: 12
logger_level: "INFO"
out_dir: "final_results/acs_linkage"
