---
# Note that this requires the scikit-learn default (non-changed) package to be installed.
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSPublicCoverage", "ACSEmployment", "ACSIncome"]
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
    adversaries:
      - adv_0:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: True
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: False
minimizers:
  - minimizer: "ibm"
    ibm_target: [0.78, 0.79, 0.8, 0.81, 0.82]
    timeout: 7200
seed: 123
device: "cpu"
num_workers: 8
logger_level: "INFO"
out_dir: "final_results/acs_ibm"
