---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSIncome"]
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
    adversaries:
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: True
minimizers:
  - minimizer: "featsel"
    featsel_k: [7, 8, 9, 10]
    method: ["anova", "chi2", "mi"]
seed: 123
device: "cpu"
num_workers: 12
logger_level: "INFO"
out_dir: "final_results/acs_feature_selection"
