---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSEmployment"]
    acs_state: "CA"
    acs_year: [2015, 2016, 2017, 2018]
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
    adversaries:
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: True
      - adv_2:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: False
minimizers:
  - minimizer: "load_multi"
    load_bucketization_folder: "bucketizations/final_results/acs_base"
seed: 123
device: "cpu"
num_workers: 12
logger_level: "INFO"
out_dir: "final_results/acs_shift"
