---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: "ACSIncome"
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
    train_percent: 1.0
    bucketization_percent: 1.0
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
    adversaries:
      - adv_2:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
      - adv_1:
        adv_type: "outlier"
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
minimizers:
  - minimizer: "tree"
    tree_max_leaf_nodes: [10, 20, 50]
    tree_min_sample_leaf: 100
    tree_alpha: [0.0, 0.3, 0.5, 0.7, 0.9]
seed: 123123
device: "cpu"
num_workers: 1
out_dir: "ablation/train_percentage"
logger_level: "STDOUT"
