---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSIncome"]
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
    train_percent: 1.0
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_tune_wd: True
    adversaries:
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        only_predict_seen: True
minimizers:
  - minimizer: "tree"
    tree_max_leaf_nodes: [2, 4, 8, 10, 20, 50, 100, 200]
    tree_min_sample_leaf: 100
    tree_alpha: [0.0, 0.3, 0.7, 0.9]
    min_bucket_threshold: [0.0]
seed: 123
device: "cpu"
num_workers: 10
out_dir: "ablation/minimal"
