---
neptune:
  enable: False
  api_key: ~
  run_name: ~
datasets:
  - dataset: ["ACSIncome"] #, "ACSPublicCoverage"] #["ACSEmployment"]
    acs_state: "CA"
    acs_year: 2014
    add_syn: False
    freeze_feature: []
    sens_feats: "disc"
    batch_size: 256
    train_percent: 1.0
    bucketization_percent:
      [1.0, 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1, 0.05, 0.01]
evaluations:
  - classifiers:
      - clf_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        clf_tune_wd: False
    adversaries:
      - adv_1:
        clf_model: "mlp2"
        clf_epochs: 20
        clf_lr: 0.01
        clf_weight_decay: 0.0
        use_only_buck_data: True
minimizers:
  # - minimizer: "tree"
  #   tree_max_leaf_nodes: [20]
  #   tree_min_sample_leaf: 100
  #   tree_alpha: [0.7]
  - minimizer: "tree"
    tree_max_leaf_nodes: [4, 10, 20, 50]
    tree_min_sample_leaf: 100
    tree_alpha: [0.0, 0.3, 0.7, 0.9]
seed: 123
device: "cpu"
num_workers: 10
out_dir: "ablation/buck_percentage_adversary_on_buck_only"
